config/routes.rb
GuessWhoRails3::Application.routes.draw do
  resources :games
  resources :messages

  devise_for :users

  root :to => "games#new"

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :messages
  belongs_to :user
  
  WORDS = ["a", "head","mouth","eye","eyes","nose","eyes on stalks","skin","one","two","three","blue","green","orange","spotty","squiggly","circular","oval","triangular","happy","sad"]
  NAMES = ["Snooz", "Zarg", "Sassle", "Gira", "Zog", "Yop", "Matag", "Pieb", "Uno", "Tonil", "Ufusi", "Veop", "Moog", "Jolod", "Pokov", "Zebo", "Hoobla", "Mush", "Gotat", "Zaphod", "Norboo", "Foobar", "Linrot", "Tag"]
  
  scope :recent, order("id DESC").limit(5)
  
  def update_state(new_state)
    self.update_attribute(:state, new_state)
    message_content = new_state.capitalize.gsub(/_/, " ")
    message_content.sub!("player1", "#{self.players.first.name}'s")
    message_content.sub!("player2", "#{self.players.last.name}'s")
    Message.create(:game_id  => self.id, :message_type  => "notification", :content => message_content)
  end
end


# == Schema Information
#
# Table name: games
#
#  id         :integer         not null, primary key
#  password   :string(255)
#  state      :string(255)
#  first_turn :integer
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, :only => :new
  before_filter :game_accessible?, :only => :show

  def new
    @previous_games = current_user.games.recent
  end

  def create
    @game = Game.new
    @game.state = "waiting_for_both_players"
    @game.password = generate_password(8)
    @game.user = current_user

    player1 = Player.new
    player1.name = params[:player1_name]
    player1.chosen_card = rand(24)
    player1.game = @game

    @player = player1

    player2 = Player.new
    player2.name = params[:player2_name]
    player2.chosen_card = rand(24)
    until player2.chosen_card != player1.chosen_card
      player2.chosen_card = rand(24)
    end
    player2.game = @game

    Game.transaction do
      player1.save
      player2.save
      if params[:first_turn] == "1"
        @game.first_turn = player1.id
      else
        @game.first_turn = player2.id
      end
      @game.save
    end
    @words = Game::WORDS
    render :show
  end

  def show
    if current_user
      @player = @game.players.first
    else
      @player = @game.players.last
      if @game.state == "waiting_for_both_players"
        Message.create(:game_id  => @game.id, :message_type  => "notification", :content => "Both players are ready to play")
        if @game.first_turn == @game.players.first.id
          @game.update_state("waiting_for_player1_question")
        else
          @game.update_state("waiting_for_player2_question")
        end
      end
    end  # player 2
    @words = Game::WORDS
  end
  
  def destroy
    @game = Game.find(params[:id])
    @final_card = params[:final_card]
    @player = Player.find(params[:player_id])
    other_player = (@game.players - [@player.id]).first

    if @final_card.to_i == other_player.chosen_card
      @game.update_state("#{@player.name} won")
    else
      @game.update_state("#{other_player.name} won")
    end
  end

  private
  def generate_password(len = 8 )
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    password = ""
    1.upto(len) { |i| password << chars[rand(chars.size-1)] }
    return password
  end
  def game_accessible?
    if @game.nil?
      @game = Game.find(params[:id])
      if current_user.nil?
        if @game.password != params[:password]
          flash[:error] = "You do not have permissions to access that game. If you would like to start a new game please fill in the details below"
          redirect_to root_path
        end
      else
        if @game.user != current_user
          flash[:error] = "You do not have permissions to access that game. If you would like to start a new game please fill in the details below"
          redirect_to root_path
        end
      end
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_card.html.erb
<div id="card-<%= defined?(card_counter) ? card_counter + 1 : 24 %>" class="card">
  <div <%= "class='card_wrapper'" if defined?(card_counter) %> >
    <div>
    <%= image_tag "#{card}.png", :class => "quickFlipCta front_of_card" %>
    </div>
    <%- if defined?(card_counter) %>
      <div>
      <%= image_tag "eliminated.png", :class => "quickFlipCta back_of_card" %>
    </div>
    <%- else -%>
      <div>
        <b>Your card</b>
      </div>
    <%- end -%>
  </div>
  <div><%= Game::NAMES[card-1] %></div>
</div>

app/views/games/_word_button.html.erb
<div class="word_button"><%= word_button %></div>

app/views/games/new.html.erb
<h1>Start a new game</h1>
<%= form_tag :controller => "games" %>
  <table>
		<tr>
			<td><label for="player1_name">Your Name:</label></td> 
			<td><%= text_field_tag "player1_name" %></td>
		</tr>
		<tr>
		<tr>
			<td><label for="player2_name">Player 2 name:</label></td> 
			<td><%= text_field_tag "player2_name" %></td>
		</tr>
		<tr>
			<td><label for="first_turn">Which Player will have the first turn?</label></td> 
			<td><%= select_tag "first_turn", options_for_select(['1', '2']) %></td>
		</tr>
	</table>
	<%= submit_tag "Create game" %>
  <h2>Previous Games</h2>
  <table>
  <%- @previous_games.each do |game| -%>
    <tr>
      <td>
        <%- if game.state =~ /won/ -%>
          <%- if game.state =~ /player1_won/ -%>
            You won
          <%- else -%>
            <%= game.players.last.name %> won
          <%- end -%>
        <%- else -%>
          <%= link_to "Enter game", game_url(game) %>
        <%- end -%>
      </td>
      <td>
        <%- if game.state =~ /won/ -%>
          &nbsp;
        <%- else -%>
          <%= link_to "Link for other player", game_url(game, :password => game.password) %>
        <%- end -%>
      </td>
      <td>
        <%- if game.state =~ /won/ -%>
          &nbsp;
        <%- else -%>
          <%= game.state.capitalize.gsub(/_/, " ") %>
        <%- end -%>
      </td>
    </tr>
    <%- end -%>
    </table>
</form>

  

app/views/games/show.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "soundmanager2-jsmin" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery.jscrollpane.min", "jquery.mousewheel", "jquery.quickflip.min", "jquery.periodic", "jquery.reveal" %>
<% end %>
<!-- Top Image-->
<div id="top_image">
	<%= image_tag "guess_who.png" %><br>
	<%= link_to "Link for other player", game_url(@game, :password => @game.password) , :id => "other_player_link" if current_user %>
</div>
<!-- Cards -->
<%= render :partial => "card", :collection => (1..24).to_a - [@player.chosen_card] %>
<%= render :partial => "card", :object => @player.chosen_card%>
<!-- Ask a question panel -->
<div id="question_panel">
  <%= form_tag messages_path, :remote => true, :id => "question_form" %>
    <%= hidden_field_tag "message[message_type]", "question", :id => "question_message_type" %>
    <%= hidden_field_tag "message[game_id]", @game.id, :id => "question_game_id" %>
    <%= hidden_field_tag "message[player_id]", @player.id, :id => "question_player_id" %>
    <span class="question">Does your alien have </span><%= text_field_tag 'message[content]', '', :size => "30" , :class => "question", :id => "question_content" %><span class="question">?</span>
    	<%= submit_tag 'Send Question', :id => "question_submit" %><br/>
    <%= render :partial => "word_button", :collection => @words %>
  </form>
</div>
<!-- Message Panel -->
<div id="message_panel">
</div>
<!-- Response Panel -->
<div id="response_panel">
  <!-- Chat -->
  <%= form_tag messages_path, :remote => true, :id => "chat_form" %>
    <%= hidden_field_tag "message[message_type]", "chat", :id => "chat_message_type"  %>
    <%= hidden_field_tag "message[game_id]", @game.id, :id => "chat_game_id"  %>
    <%= hidden_field_tag "message[player_id]", @player.id, :id => "chat_player_id"  %>
    <%= text_area_tag "message[content]", "", :cols => 26, :rows => 4, :id => "chat_content" %>
    <%= image_submit_tag "chat_button.png", :id => "chat_button" %>
  </form><br/>
  <div id="yes_button" class="yes_button" message_type="response", message_content="Yes", game_id="<%= @game.id %>" player_id="<%= @player.id %>">
    Yes
  </div>
  <div id="no_button" class="no_button" message_type="response", message_content="No", game_id="<%= @game.id %>" player_id="<%= @player.id %>">
    No
  </div>
  <br><br><br>
  <div class="guess_button">
    I think I can guess
  </div>
  <!-- <%= link_to "Stop", "#", :id => "stop" %>
  <%= link_to "Start", "#", :id => "start" %> -->
</div>
<div id="notice_modal" class="reveal-modal">
     <h1>Almost there!</h1>
     <p id="notice_modal_content"></p>
     <a class="close-reveal-modal">&#215;</a>
</div>